// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SearchApi.Models;

namespace SearchApi.Migrations
{
    [DbContext(typeof(AddressContext))]
    [Migration("20190331085116_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SearchApi.Models.AddressItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DwellingNumber");

                    b.Property<string>("DwellingType");

                    b.Property<string>("Location");

                    b.Property<string>("Longitude");

                    b.Property<string>("StreetAddress")
                        .IsRequired();

                    b.Property<string>("Suburb")
                        .IsRequired();

                    b.Property<string>("Xcoordinate");

                    b.HasKey("Id");

                    b.ToTable("AddressItems");
                });
#pragma warning restore 612, 618
        }
    }
}
